#!/usr/bin/env bash

set -e
set -u

infile="$1"
outfile="$(mktemp).html"

cat "$infile" | uv run main.py > $outfile

if [[ "$(uname)" == "Darwin" ]]; then
    open "$outfile"
else
    xdg-open "$outfile"
fi

echo "$infile" | entr -s "cat $infile | uv run main.py > $outfile"

